@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###### bozo
GET     http://{{host}}/snark

###### get
GET http://{{host}}/api/blogs HTTP/1.1

### post
POST http://{{host}}/api/blogs HTTP/1.1
Content-Type: {{contentType}}

{
    "title":    "newtitle",
    "author":   "author",
    "url":      "url",
    "likes":    52402
}