### Root
GET         https://dry-sands-31178.herokuapp.com/

### Persons list
GET         https://dry-sands-31178.herokuapp.com/api/persons

### Info
GET         https://dry-sands-31178.herokuapp.com/info

### Single Request (malformed)
GET         https://dry-sands-31178.herokuapp.com/api/persons/3

### Single Request = exists
GET         https://dry-sands-31178.herokuapp.com/api/persons/5dc9ee7fbcca7238d0d13df7

### Single Request = not exists 204 No Content
GET         https://dry-sands-31178.herokuapp.com/api/persons/5dc9ee7fbcca7238d0d13df9


### Delete a Sengle Record    -- 204 No Content
DELETE      https://dry-sands-31178.herokuapp.com/api/persons/5dc9ee7fbcca7238d0d13df7

### Post new Record
POST        https://dry-sands-31178.herokuapp.com/api/persons
Content-Type: application/json

{
      "name": "Bond, James Bond",
      "number": "007"
}

### Post with name missing
POST        https://dry-sands-31178.herokuapp.com/api/persons
Content-Type: application/json

{
      "number": "007"
}

### Post with number missing
POST        https://dry-sands-31178.herokuapp.com/api/persons
Content-Type: application/json

{
      "name": "Bond, James Bond"
}

### Post with non-unique name 
POST        https://dry-sands-31178.herokuapp.com/api/persons
Content-Type: application/json

{
      "name": "Ada Lovelace",
      "number": "39-44-5323523"
}


